/**
 * Compiles a flex spec: parses the spec, then the C in %top, %{ %},
 * actions, and user code (in text order, so #define and typedef work as in
 * C), and runs the compile-time checks.
 */
import type { Diagnostic } from '$lib/theory/diagnostics';
import type { FnDef, Stmt, TopItem } from './c-ast';
import { checkFunction, checkGlobals, checkScanner } from './c-check';
import { lexC, type Macros } from './c-lexer';
import { parseBody, parseTop, type Typedefs } from './c-parser';
import { BUILTIN_FUNCTIONS } from './c';
import { parseSpec, type FlexSpec } from './spec';

/** Globals flex defines; user code may only declare them `extern`. */
export const FLEX_GLOBALS = ['yytext', 'yyleng', 'yylineno', 'yyin', 'yyout'];
const PROVIDED = [...FLEX_GLOBALS, 'stdin', 'stdout', 'stderr', 'EOF', 'NULL', 'INITIAL'];

export interface CompiledSpec {
	spec: FlexSpec;
	/** Global declarations from %top, %{ %}, and user code, in text order. */
	globals: Stmt[];
	functions: Map<string, FnDef>;
	/** Code before the first rule: runs each time yylex is called. */
	prologue: Stmt[];
	/** Parsed action per rule (empty for | and <<EOF>> rules without code). */
	actions: Stmt[][];
	/** #define names with a single number or character value. */
	defines: Map<string, number>;
	/** Globals the program declares. */
	declared: Set<string>;
	/** Declared globals that are numeric scalars (int, double, …), for the word-count view. */
	numeric: Set<string>;
	diagnostics: Diagnostic[];
	/** No errors: the scanner can run. */
	ok: boolean;
}

interface Unit {
	start: number;
	end: number;
	kind: 'top' | 'body';
	/** Rule index for actions; -1 for the prologue. */
	rule: number | null;
}

export function compileSpec(text: string): CompiledSpec {
	const spec = parseSpec(text);
	try {
		return compile(spec);
	} catch (e) {
		// A limit of the JavaScript engine (e.g. the call stack) on extreme input.
		const message = `the spec could not be compiled here (${e instanceof Error ? e.message : String(e)})`;
		return {
			spec,
			globals: [],
			functions: new Map(),
			prologue: [],
			actions: spec.rules.map(() => []),
			defines: new Map(),
			declared: new Set(),
			numeric: new Set(),
			diagnostics: [...spec.diagnostics, { severity: 'error', message }],
			ok: false
		};
	}
}

function compile(spec: FlexSpec): CompiledSpec {
	const text = spec.text;
	const diagnostics: Diagnostic[] = [...spec.diagnostics];
	const macros: Macros = new Map();
	const typedefs: Typedefs = new Map();

	const units: Unit[] = [];
	for (const b of spec.blocks) {
		units.push({
			start: b.start,
			end: b.end,
			kind: b.kind === 'prologue' ? 'body' : 'top',
			rule: b.kind === 'prologue' ? -1 : null
		});
	}
	for (const r of spec.rules) {
		if (!r.bar && r.actionEnd > r.actionStart)
			units.push({ start: r.actionStart, end: r.actionEnd, kind: 'body', rule: r.index });
	}
	units.sort((a, b) => a.start - b.start);

	const top: TopItem[] = [];
	const prologue: Stmt[] = [];
	const actions: Stmt[][] = spec.rules.map(() => []);
	for (const u of units) {
		const lexed = lexC(text, u.start, u.end, macros);
		diagnostics.push(...lexed.diagnostics);
		if (u.kind === 'top') {
			const res = parseTop(lexed.tokens, typedefs);
			diagnostics.push(...res.diagnostics);
			top.push(...res.items);
		} else {
			const res = parseBody(lexed.tokens, typedefs);
			diagnostics.push(...res.diagnostics);
			if (u.rule === -1) prologue.push(...res.body);
			else actions[u.rule!] = res.body;
		}
	}

	const error = (message: string, start: number, end: number) =>
		diagnostics.push({ severity: 'error', message, span: { start, end, source: null } });

	// Globals and functions.
	const globals: Stmt[] = [];
	const functions = new Map<string, FnDef>();
	const names = new Set<string>(PROVIDED);
	const constants = new Set<string>(['EOF', 'NULL', 'INITIAL']);
	for (const sc of spec.startConditions) {
		names.add(sc.name);
		constants.add(sc.name);
	}
	const declared = new Set<string>();
	const numeric = new Set<string>();
	/** Names that exist before any global is initialized. */
	const initial = new Set(names);
	for (const item of top) {
		if (item.k === 'fn') {
			const fn = item.fn;
			if (fn.name === 'yylex')
				error('yylex is generated by flex; do not define it', fn.nameLoc.start, fn.nameLoc.end);
			else if (functions.has(fn.name))
				error(`function ${fn.name} is defined twice`, fn.nameLoc.start, fn.nameLoc.end);
			else functions.set(fn.name, fn);
			continue;
		}
		if (item.k === 'proto') continue;
		const s = item.stmt;
		if (s.k === 'decl') {
			for (const d of s.decls) {
				if (s.extern) {
					names.add(d.name);
					initial.add(d.name);
					continue;
				}
				if (FLEX_GLOBALS.includes(d.name) || PROVIDED.includes(d.name))
					error(
						`${d.name} is defined by flex; declare it with extern if needed`,
						d.loc.start,
						d.loc.end
					);
				else if (declared.has(d.name))
					error(`${d.name} is already declared`, d.loc.start, d.loc.end);
				declared.add(d.name);
				names.add(d.name);
				if (
					d.array === undefined &&
					d.type.ptr === 0 &&
					d.type.base !== 'FILE' &&
					d.type.base !== 'void'
				)
					numeric.add(d.name);
			}
			if (!s.extern) globals.push(s);
		} else if (s.k === 'enum') {
			for (const it of s.items) {
				names.add(it.name);
				constants.add(it.name);
			}
			globals.push(s);
		}
	}

	const scope = {
		globals: names,
		constants,
		functions: new Map(
			[...functions].map(([n, f]) => [n, { params: f.params.length, variadic: f.variadic }])
		)
	};
	diagnostics.push(
		...checkGlobals(globals, {
			globals: initial,
			functions: scope.functions,
			startConditions: spec.startConditions.map((sc) => sc.name)
		})
	);
	for (const fn of functions.values()) diagnostics.push(...checkFunction(fn, scope));
	const checked = checkScanner(prologue, actions, scope);
	diagnostics.push(...checked.prologue, ...checked.actions.flat());

	const main = functions.get('main');
	if (main && main.params.length > 2)
		error('main takes at most two parameters (argc, argv)', main.nameLoc.start, main.nameLoc.end);
	for (const fn of functions.values()) {
		if (BUILTIN_FUNCTIONS.has(fn.name) && fn.name !== 'yywrap' && fn.name !== 'yylex')
			diagnostics.push({
				severity: 'warning',
				message: `${fn.name} replaces the library function of the same name`,
				span: { start: fn.nameLoc.start, end: fn.nameLoc.end, source: null }
			});
	}
	if (!spec.options.has('yylineno')) {
		const use = /\byylineno\b/.exec(text);
		if (use && spec.rules.length)
			diagnostics.push({
				severity: 'info',
				message: 'yylineno counts lines only with %option yylineno; without it, it stays 1',
				span: { start: use.index, end: use.index + 8, source: null }
			});
	}

	const defines = new Map<string, number>();
	for (const [name, body] of macros) {
		if (body.length === 1 && (body[0].kind === 'int' || body[0].kind === 'char'))
			defines.set(name, body[0].value as number);
		if (
			body.length === 2 &&
			body[0].kind === 'punct' &&
			body[0].text === '-' &&
			body[1].kind === 'int'
		)
			defines.set(name, -(body[1].value as number));
	}

	diagnostics.sort((a, b) => (a.span?.start ?? 0) - (b.span?.start ?? 0));
	const ok = !diagnostics.some((x) => x.severity === 'error');
	return {
		spec,
		globals,
		functions,
		prologue,
		actions,
		defines,
		declared,
		numeric,
		diagnostics: dedupe(diagnostics),
		ok
	};
}

function dedupe(ds: Diagnostic[]): Diagnostic[] {
	const seen = new Set<string>();
	return ds.filter((d) => {
		const key = `${d.severity}|${d.message}|${d.span?.start}|${d.span?.end}`;
		if (seen.has(key)) return false;
		seen.add(key);
		return true;
	});
}
