/**
 * Bootstrapping a compiler, as on Intro (cont’d), slide 8: given machine M and
 * language L, the goal is T(L → M / M), "but tough directly!". Step 1 runs T(L → M / L′) through
 * T(L′ → M′ / M); step 2 runs it again through the result of step 1. L′ is a
 * simple subset of L, and M′ is inefficient M-code.
 *
 * Both rows are computed with `compose`, so the figure and the captions follow
 * the composition rule rather than restating it.
 */
import {
	equationLayout,
	FIGURE_METRICS,
	minFitWidth,
	tGeometry,
	type EquationLayout,
	type Metrics,
	type Point,
	type TGeom
} from './geometry';
import { compose, type Composition, type Facts, type Piece, type TDiagram } from './model';

/** L′ ⊆ L; M and M′ run directly (M′ is inefficient M-code, so it runs on M). */
export const BOOTSTRAP_FACTS: Facts = {
	subsets: [{ sub: 'L′', sup: 'L' }],
	runnable: ['M', 'M′']
};

/** "Want this": an L → M compiler that runs on M. */
export const WANT: TDiagram = { source: 'L', target: 'M', host: 'M' };
/** The real L → M compiler, written in the subset L′. */
export const COMPILER_IN_SUBSET: TDiagram = { source: 'L', target: 'M', host: 'L′' };
/** A quick compiler for L′, written in M, that emits inefficient M-code. */
export const QUICK_COMPILER: TDiagram = { source: 'L′', target: 'M′', host: 'M' };

export interface BootstrapRow {
	label: string;
	program: TDiagram;
	translator: TDiagram;
	composition: Composition;
	result: TDiagram;
}

/** Rows 1) and 2) of the slide. */
export function bootstrapRows(): BootstrapRow[] {
	const first = compose(COMPILER_IN_SUBSET, QUICK_COMPILER, BOOTSTRAP_FACTS);
	if (!first.result) throw new Error('Bootstrapping step 1 does not compose');
	const second = compose(COMPILER_IN_SUBSET, first.result, BOOTSTRAP_FACTS);
	if (!second.result) throw new Error('Bootstrapping step 2 does not compose');
	return [
		{
			label: '1)',
			program: COMPILER_IN_SUBSET,
			translator: QUICK_COMPILER,
			composition: first,
			result: first.result
		},
		{
			label: '2)',
			program: COMPILER_IN_SUBSET,
			translator: first.result,
			composition: second,
			result: second.result
		}
	];
}

/** How much of a row is drawn at a step. */
export type RowPhase = 'hidden' | 'pair' | 'result';

export interface WalkStep {
	/** Phase of rows 1) and 2). */
	rows: [RowPhase, RowPhase];
	/** What to mark: where the stem meets the arm, or the new result's stem. */
	focus: { row: 0 | 1; part: 'meet' | 'result' } | null;
	goalMet: boolean;
	pieces: Piece[];
}

const L = (lang: string): Piece => ({ lang });

/** The five steps: the goal, then each row's pair and its result. */
export function bootstrapSteps(rows = bootstrapRows()): WalkStep[] {
	const [one, two] = rows;
	return [
		{
			rows: ['hidden', 'hidden'],
			focus: null,
			goalMet: false,
			pieces: [
				'Given machine ',
				L('M'),
				' and language ',
				L('L'),
				', we want ',
				{ t: WANT },
				': an ',
				L('L'),
				' → ',
				L('M'),
				' compiler that runs on ',
				L('M'),
				'. Writing it directly is tough.'
			]
		},
		{
			rows: ['pair', 'hidden'],
			focus: { row: 0, part: 'meet' },
			goalMet: false,
			pieces: [
				'1) Write the ',
				L('L'),
				' → ',
				L('M'),
				' compiler in ',
				L('L′'),
				', a simple subset of ',
				L('L'),
				': ',
				{ t: one.program },
				'. Compile it with ',
				{ t: one.translator },
				', a compiler for ',
				L('L′'),
				' written in ',
				L('M'),
				' that emits ',
				L('M′'),
				', inefficient M-code. Its stem ',
				L(one.program.host),
				' meets the left arm ',
				L(one.translator.source),
				', and ',
				L(one.translator.host),
				' runs directly.'
			]
		},
		{
			rows: ['result', 'hidden'],
			focus: { row: 0, part: 'result' },
			goalMet: false,
			pieces: [
				'= ',
				{ t: one.result },
				': the same compiler, now written in ',
				L(one.result.host),
				'. It generates good ',
				L('M'),
				' code but itself runs slowly.'
			]
		},
		{
			rows: ['result', 'pair'],
			focus: { row: 1, part: 'meet' },
			goalMet: false,
			pieces: [
				'2) Compile ',
				{ t: two.program },
				' again, this time with ',
				{ t: two.translator },
				' from step 1. Its stem ',
				L(two.program.host),
				' meets the left arm ',
				L(two.translator.source),
				': allowed because ',
				L('L′'),
				' ⊆ ',
				L('L'),
				'. The translator is ',
				L(two.translator.host),
				' code, which runs on ',
				L('M'),
				'.'
			]
		},
		{
			rows: ['result', 'result'],
			focus: { row: 1, part: 'result' },
			goalMet: true,
			pieces: [
				'= ',
				{ t: two.result },
				': the compiler is now ',
				L(two.result.host),
				' code generated by the ',
				L('L'),
				' → ',
				L('M'),
				' compiler itself, so it is efficient. This is the compiler we wanted.'
			]
		}
	];
}

export interface FigureRow {
	label: string;
	/** Baseline of the row label ("1)"). */
	labelAt: Point;
	/** Absolute positions (the layout's points shifted by the row's origin). */
	layout: EquationLayout;
	geoms: { program: TGeom; translator: TGeom; result: TGeom };
	row: BootstrapRow;
}

/** Two lines of the slide's prose: first baseline, line height, and the lines. */
export interface FigureText {
	x: number;
	y: number;
	lineHeight: number;
	lines: [string, string];
}

/**
 * How the figure is arranged: as on the slide, or stacked for a phone so it
 * does not have to shrink its labels.
 */
export type FigureLayout = 'slide' | 'narrow';

export interface FigureArrow {
	x1: number;
	y1: number;
	x2: number;
	y2: number;
	/** "Want this": centered above a horizontal arrow, start-anchored beside a vertical one. */
	label: Point & { anchor: 'middle' | 'start' };
}

export interface BootstrapFigure {
	layout: FigureLayout;
	width: number;
	height: number;
	metrics: Metrics;
	/** "Given machine M" / "and language L": first baseline and line height. */
	given: FigureText;
	/** The "Want this" arrow into the goal. */
	arrow: FigureArrow;
	goal: { pos: Point; geom: TGeom };
	/** "But tough" / "directly!", to the right of the goal. */
	tough: FigureText;
	rows: FigureRow[];
}

const LABEL_W = 30;
const ROW_GAP = 34;
/** Room between the goal and "But tough directly!" (clears the check mark on the goal's corner). */
const TOUGH_GAP = 20;
/** Length of the "Want this" arrow when it points down into the goal (narrow layout). */
const WANT_DROP = 32;
/** Size of the figure's prose ("Given machine M…"), in px. */
export const FIGURE_TEXT_SIZE = 16;
/** Size of the "Want this" label, in px. */
export const WANT_LABEL_SIZE = 14;
/** Average advance of the sans-serif UI font, in em. */
const SANS_ADVANCE = 0.56;

/**
 * Positions for the whole slide figure; rows line up their "=" and results.
 *
 * - `slide`: as on the slide. "Given machine M and language L" and the "Want
 *   this" arrow lead into the goal from the left, "But tough directly!" is to
 *   its right, and the rows' results form a column under the goal.
 * - `narrow`: the prose is above the goal and the arrow points down into it;
 *   each row's "=" and result go below its pair (see `equationLayout`'s
 *   `stacked`). The goal, the programs and the results share one column.
 */
export function bootstrapFigure(
	m: Metrics = FIGURE_METRICS,
	layout: FigureLayout = 'slide'
): BootstrapFigure {
	const rows = bootstrapRows();
	const u = m.unit;
	const narrow = layout === 'narrow';
	const built = rows.map((row) => {
		const geoms = {
			program: tGeometry(row.program, m),
			translator: tGeometry(row.translator, m),
			result: tGeometry(row.result, m)
		};
		return {
			row,
			geoms,
			eq: equationLayout(geoms.program, geoms.translator, geoms.result, {
				snapped: true,
				stacked: narrow
			})
		};
	});
	const column = Math.max(...built.map((b) => b.eq.result!.x));
	/** Left edge of the rows: after the row labels, or (narrow) at 0, where "=" gives them a column. */
	const ox = narrow ? 0 : LABEL_W;
	const goalGeom = tGeometry(WANT, m);
	const goalX = ox + column;
	const lines: [string, string] = ['Given machine M', 'and language L'];
	const toughLines: [string, string] = ['But tough', 'directly!'];
	const proseW = (l: readonly string[]) =>
		Math.max(...l.map((s) => s.length * FIGURE_TEXT_SIZE * SANS_ADVANCE));
	const textW = proseW(lines);
	const lineHeight = Math.round(FIGURE_TEXT_SIZE * 1.35);
	/** First baseline of two lines centered on the goal's crossbar, below the goal's top. */
	const proseDy = Math.round(u / 2 - lineHeight / 2 + FIGURE_TEXT_SIZE * 0.36);

	let given: FigureText;
	let arrow: FigureArrow;
	let goalY: number;
	if (narrow) {
		given = { x: 0, y: Math.round(FIGURE_TEXT_SIZE * 0.8), lineHeight, lines };
		const x = goalX + Math.round(goalGeom.stemX / 2);
		const y1 = given.y + lineHeight + 9;
		const y2 = y1 + WANT_DROP;
		goalY = y2 + 6;
		arrow = {
			x1: x,
			y1,
			x2: x,
			y2,
			label: {
				x: x + 9,
				y: Math.round((y1 + y2) / 2 + WANT_LABEL_SIZE * 0.36),
				anchor: 'start'
			}
		};
	} else {
		goalY = 0;
		given = { x: 0, y: proseDy, lineHeight, lines };
		const y = Math.round(u / 2);
		arrow = {
			x1: Math.round(textW + 10),
			y1: y,
			x2: goalX - 6,
			y2: y,
			label: {
				x: Math.round((textW + 10 + goalX - 6) / 2),
				y: Math.round(u / 2 - 7),
				anchor: 'middle'
			}
		};
	}
	const tough: FigureText = {
		x: goalX + goalGeom.width + TOUGH_GAP,
		y: goalY + proseDy,
		lineHeight,
		lines: toughLines
	};
	const wantW = 'Want this'.length * WANT_LABEL_SIZE * SANS_ADVANCE;

	let y = goalY + 2 * u + ROW_GAP;
	let right = Math.max(
		tough.x + proseW(toughLines),
		textW,
		arrow.label.anchor === 'start' ? arrow.label.x + wantW : arrow.label.x + wantW / 2
	);
	const figureRows: FigureRow[] = built.map((b) => {
		const shift = column - b.eq.result!.x;
		const oy = y;
		const layout: EquationLayout = {
			program: { x: ox + b.eq.program.x, y: oy + b.eq.program.y },
			translator: { x: ox + b.eq.translator.x, y: oy + b.eq.translator.y },
			equals: { x: ox + b.eq.equals!.x + shift, y: oy + b.eq.equals!.y },
			result: { x: ox + column, y: oy + b.eq.result!.y },
			width: b.eq.width + shift,
			height: b.eq.height
		};
		right = Math.max(right, ox + b.eq.width + shift);
		y += b.eq.height + ROW_GAP;
		return {
			label: b.row.label,
			labelAt: { x: 0, y: Math.round(oy + u / 2 + m.font * 0.36) },
			layout,
			geoms: b.geoms,
			row: b.row
		};
	});

	return {
		layout,
		width: Math.ceil(right),
		height: y - ROW_GAP,
		metrics: m,
		given,
		arrow,
		goal: { pos: { x: goalX, y: goalY }, geom: goalGeom },
		tough,
		rows: figureRows
	};
}

/** Room the figure's SVG leaves around the drawing (the goal's check mark pokes out above it). */
export const FIGURE_PAD = { left: 6, top: 16, right: 8, bottom: 8 } as const;

/** Width of the figure's SVG viewBox, in drawing units. */
export function figureViewWidth(fig: BootstrapFigure): number {
	return fig.width + FIGURE_PAD.left + FIGURE_PAD.right;
}

/**
 * Below this box width (px) the slide layout would draw its T-diagram labels
 * under `MIN_LABEL_PX`, so the figure switches to the narrow layout.
 * BootstrapFigure.svelte's container query uses this number.
 */
export const FIGURE_NARROW_BELOW = minFitWidth(
	figureViewWidth(bootstrapFigure()),
	FIGURE_METRICS.font
);
